export type AlertCondition = "RSI_THRESHOLD" | "PRICE_CROSS" | "REGIME_CHANGE" | "BULLISH_BOS";
export type AlertChannel = "WEB" | "EMAIL" | "DISCORD";
export interface AlertRule { id: string; user_id: string; symbol: string; condition_type: AlertCondition; operator: string | null; threshold: number | null; timeframe: string; enabled: boolean; cooldown_minutes: number; channels: AlertChannel[]; state: Record<string, unknown>; last_triggered_at: string | null; created_at: string; updated_at: string; }
export interface AlertEvent { id: string; user_id: string; rule_id: string; symbol: string; condition_type: AlertCondition; title: string; message: string; payload: Record<string, unknown>; channels: AlertChannel[]; triggered_at: string; read_at: string | null; created_at: string; }
const API_BASE = (import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8000").replace(/\/$/, "");
const CSRF_STORAGE_KEY = "mr_csrf_token";
function csrf(): string | null { try { return window.sessionStorage.getItem(CSRF_STORAGE_KEY) || document.cookie.split(";").map(item => item.trim()).find(item => item.startsWith("mr_csrf="))?.slice("mr_csrf=".length) || null; } catch { return null; } }
async function ensureCsrf(): Promise<string> { const existing = csrf(); if (existing) return existing; const response = await fetch(`${API_BASE}/api/auth/csrf`, { credentials: "include" }); if (!response.ok) throw new Error("Unable to establish secure alert session."); const token = response.headers.get("X-CSRF-Token"); if (!token) throw new Error("The API did not return a CSRF token."); try { window.sessionStorage.setItem(CSRF_STORAGE_KEY, token); } catch {} return token; }
async function request<T>(path: string, init: RequestInit = {}): Promise<T> { const headers = new Headers(init.headers); if (init.body) headers.set("Content-Type", "application/json"); if (init.method && init.method !== "GET") headers.set("X-CSRF-Token", await ensureCsrf()); const response = await fetch(`${API_BASE}${path}`, { ...init, headers, credentials: "include" }); if (!response.ok) { let message = `Request failed: ${response.status}`; try { const body = await response.json() as { detail?: string }; if (body.detail) message = body.detail; } catch {} throw new Error(message); } if (response.status === 204) return undefined as T; return await response.json() as T; }
export async function getAlertRules(): Promise<AlertRule[]> { return (await request<{ items: AlertRule[] }>("/api/alerts")).items; }
export async function createAlertRule(payload: { symbol: string; condition_type: AlertCondition; operator?: string; threshold?: number; timeframe?: string; cooldown_minutes: number; channels: AlertChannel[] }): Promise<AlertRule> { return (await request<{ item: AlertRule }>("/api/alerts", { method: "POST", body: JSON.stringify(payload) })).item; }
export async function updateAlertRule(id: string, payload: Partial<AlertRule>): Promise<AlertRule> { return (await request<{ item: AlertRule }>(`/api/alerts/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify(payload) })).item; }
export async function deleteAlertRule(id: string): Promise<void> { await request<void>(`/api/alerts/${encodeURIComponent(id)}`, { method: "DELETE" }); }
export async function evaluateAlerts(): Promise<AlertEvent[]> { return (await request<{ items: AlertEvent[] }>("/api/alerts/events/evaluate", { method: "POST" })).items; }
export async function getAlertEvents(unread = false): Promise<AlertEvent[]> { const params = new URLSearchParams({ unread: String(unread), limit: "50" }); return (await request<{ items: AlertEvent[] }>(`/api/alerts/events/list?${params}`)).items; }
export async function markAlertRead(id: string): Promise<AlertEvent> { return (await request<{ item: AlertEvent }>(`/api/alerts/events/${encodeURIComponent(id)}/read`, { method: "POST" })).item; }
