import { useEffect,useState } from "react";
import { AlertTriangle, Download, KeyRound, Link2, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { API_KEY_SCOPES, WEBHOOK_EVENTS, createInfrastructureKey, createInfrastructureWebhook, deleteInfrastructureWebhook, getInfrastructureKeys, getInfrastructureWebhooks, getInfrastructureExportSchedules, createInfrastructureExportSchedule, deleteInfrastructureExportSchedule, InfrastructureApiKey, InfrastructureWebhook, InfrastructureExportSchedule } from "./api";

export default function InfrastructurePage(){
 const[keys,setKeys]=useState<InfrastructureApiKey[]>([]);const[webhooks,setWebhooks]=useState<InfrastructureWebhook[]>([]);const[exports,setExports]=useState<InfrastructureExportSchedule[]>([]);const[name,setName]=useState("Research integration");const[hookName,setHookName]=useState("Research events");const[hookUrl,setHookUrl]=useState("");const[hookEvents,setHookEvents]=useState(["research.completed","outcome.event"]);const[exportName,setExportName]=useState("Daily research dataset");const[error,setError]=useState<string|null>(null);const[secret,setSecret]=useState<string|null>(null);const[hookSecret,setHookSecret]=useState<string|null>(null);
 const load=async()=>{try{setError(null);const[k,w,e]=await Promise.all([getInfrastructureKeys(),getInfrastructureWebhooks(),getInfrastructureExportSchedules()]);setKeys(k);setWebhooks(w);setExports(e)}catch(e){setError(e instanceof Error?e.message:"Unable to load infrastructure controls.")}};useEffect(()=>{void load()},[]);
 const createKey=async()=>{try{const item=await createInfrastructureKey({name,scopes:API_KEY_SCOPES});setSecret(item.secret);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to create API key.")}};
 const createHook=async()=>{try{const item=await createInfrastructureWebhook({name:hookName,url:hookUrl,events:hookEvents});setHookSecret(item.secret);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to create webhook.")}};
 const createExport=async()=>{try{await createInfrastructureExportSchedule({name:exportName,resource_type:"RUNS",format:"JSON",interval_minutes:1440});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to create export schedule.")}};
 return <div className="app phase9-page"><main><section className="hero"><div><div className="eyebrow">Phase 9 · Premium infrastructure</div><h2>Research infrastructure control plane.</h2><p>Programmable access, event delivery, reproducible datasets and collaboration.</p></div><div className="hero-stat"><ShieldCheck size={20}/><strong>API · MCP · Webhooks</strong><span>controlled infrastructure</span></div></section>{error&&<div className="error"><AlertTriangle size={17}/>{error}</div>}{secret&&<section className="panel phase9-secret"><strong>New API key</strong><code>{secret}</code></section>}{hookSecret&&<section className="panel phase9-secret"><strong>New webhook secret</strong><code>{hookSecret}</code></section>}
 <section className="panel"><div className="panel-head"><div><h3><KeyRound size={17}/> API access</h3><span>Scoped bearer keys.</span></div></div><div className="phase9-form"><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><button onClick={()=>void createKey()}><Plus size={15}/>Create API key</button></div><div className="phase9-list">{keys.map(k=><article key={k.id}><div><strong>{k.name}</strong><span>{k.key_prefix} · {k.scopes.length} scopes · {k.active?"active":"revoked"}</span></div>{k.active&&<button className="icon-button danger" onClick={()=>void import("./api").then(x=>x.revokeInfrastructureKey(k.id))}><Trash2 size={14}/></button>}</article>)}</div></section>
 <section className="panel"><div className="panel-head"><div><h3><Link2 size={17}/> Webhooks</h3><span>Signed, queued research events.</span></div></div><div className="phase9-form"><label>Name<input value={hookName} onChange={e=>setHookName(e.target.value)}/></label><label>Endpoint<input value={hookUrl} onChange={e=>setHookUrl(e.target.value)} placeholder="https://example.com/events"/></label><button onClick={()=>void createHook()} disabled={!hookUrl.trim()}><Plus size={15}/>Create webhook</button></div><div className="phase9-list">{webhooks.map(w=><article key={w.id}><div><strong>{w.name}</strong><span>{w.url} · {w.events.join(", ")}</span></div><button className="icon-button danger" onClick={()=>void deleteInfrastructureWebhook(w.id)}><Trash2 size={14}/></button></article>)}</div><p className="muted">Supported events: {WEBHOOK_EVENTS.join(", ")}</p></section>
 <section className="panel"><div className="panel-head"><div><h3><Download size={17}/> Scheduled exports</h3><span>JSON/CSV research datasets with reproducibility metadata.</span></div></div><div className="phase9-form"><label>Name<input value={exportName} onChange={e=>setExportName(e.target.value)}/></label><button onClick={()=>void createExport()}><Plus size={15}/>Schedule daily export</button></div><div className="phase9-list">{exports.map(e=><article key={e.id}><div><strong>{e.name}</strong><span>{e.resource_type} · {e.format} · next {new Date(e.next_run_at).toLocaleString()}</span></div><button className="icon-button danger" onClick={()=>void deleteInfrastructureExportSchedule(e.id)}><Trash2 size={14}/></button></article>)}</div></section><footer>Infrastructure access is scoped and metered.</footer></main></div>;
}
