import { useCallback,useEffect,useMemo,useState } from "react";
import { Activity, BrainCircuit, Database, RefreshCw, ShieldCheck, Sparkles } from "lucide-react";
import { ApiError, getMarketStructure, getTechnicalAnalysis, TechnicalAnalysis, User } from "./api";
import { getNewsResearch, FundamentalEvent } from "./newsApi";
import { createChartEvent, createFundamental, createPhase10Model, createPhase10ModelVersion, evaluatePhase10Model, getChartEvents, getFundamentals, getPhase10Models, getPhase10Overview, promotePhase10Model, rollbackPhase10Model, trackPhase10ProductEvent, ChartEvent, FundamentalObservation, Phase10Overview, ResearchModel } from "./phase10Api";
import AdvancedResearchChart from "./AdvancedResearchChart";

type Props={user:User;onLogout:()=>void};
const SYMBOLS=["BTC/USD","ETH/USD","SOL/USD","EUR/USD","GBP/USD","USD/JPY","NVDA","AAPL","MSFT","SPY"];
const TIMEFRAMES=["15m","1h","4h","1d"];
function fmtTime(value:string|null|undefined){if(!value)return "—";const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString();}
function providerEventToChart(item:FundamentalEvent):ChartEvent{return {id:`fundamental-${item.id}`,symbol:item.affected_assets[0]??"",timeframe:"1h",event_type:"CATALYST",occurred_at:item.event_timestamp,price:null,payload:{title:item.title,event_type:item.event_type,actual:item.actual,estimate:item.estimate,previous:item.previous,surprise:item.surprise,importance:item.importance},source:item.provider,engine_version:"fundamental-provider"};}
function structureEventToChart(item:{type:string;time:string;price:number}):ChartEvent{const type=item.type.startsWith("BOS_")?"BOS":item.type.startsWith("CHOCH_")?"CHOCH":item.type.includes("LIQUIDITY")||item.type.includes("STOP_RUN")||item.type.includes("EQUAL_")?"LIQUIDITY":"SMC";return {id:`structure-${item.time}-${item.type}`,symbol:"",timeframe:"1h",event_type:type,occurred_at:item.time,price:item.price,payload:{source_type:item.type},source:"market-structure",engine_version:"phase6-structure-v1"};}

export default function Phase10Page({user,onLogout}:Props){
 const [symbol,setSymbol]=useState("BTC/USD"); const [timeframe,setTimeframe]=useState("1h"); const [analysis,setAnalysis]=useState<TechnicalAnalysis|null>(null); const [storedEvents,setStoredEvents]=useState<ChartEvent[]>([]); const [structureEvents,setStructureEvents]=useState<ChartEvent[]>([]); const [fundamentals,setFundamentals]=useState<FundamentalObservation[]>([]); const [providerFundamentals,setProviderFundamentals]=useState<FundamentalEvent[]>([]); const [overview,setOverview]=useState<Phase10Overview|null>(null); const [models,setModels]=useState<ResearchModel[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{try{setError(null);const [o,m,a,e,f,n,s]=await Promise.all([getPhase10Overview(),getPhase10Models(),getTechnicalAnalysis(symbol,timeframe,250),getChartEvents(symbol,timeframe),getFundamentals(symbol),getNewsResearch(symbol,30,50),getMarketStructure(symbol,timeframe,250)]);setOverview(o);setModels(m.items);setAnalysis(a);setStoredEvents(e.items);setFundamentals(f.items);setProviderFundamentals(n.fundamental_events);setStructureEvents(s.events.map(structureEventToChart));}catch(e){if(e instanceof ApiError&&e.status===401){onLogout();return}setError(e instanceof Error?e.message:"Unable to load Phase 10 intelligence.");}},[onLogout,symbol,timeframe]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{void trackPhase10ProductEvent("phase10.view","advanced_intelligence",{symbol,timeframe}).catch(()=>{});},[symbol,timeframe]);
 const chartEvents=useMemo(()=>[...structureEvents,...storedEvents,...providerFundamentals.filter(e=>e.affected_assets.some(asset=>asset.toUpperCase()===symbol.toUpperCase())).map(providerEventToChart)].sort((a,b)=>Date.parse(a.occurred_at)-Date.parse(b.occurred_at)),[providerFundamentals,storedEvents,structureEvents,symbol]);
 const eventCount=chartEvents.length;
 const addResearchEvent=async()=>{try{setBusy(true);await createChartEvent({symbol,timeframe,event_type:"RESEARCH",payload:{note:"Manual research annotation",source:"phase10-workspace"},price:analysis?.candles.filter(c=>c.is_complete).at(-1)?.close});void trackPhase10ProductEvent("phase10.research_annotation","advanced_charting",{symbol,timeframe});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to add research event.");}finally{setBusy(false);}};
 const recordFundamental=async()=>{try{setBusy(true);await createFundamental({symbol,observation_type:"FUNDAMENTAL_TREND",source:"research-workspace",source_version:"phase10-ui-v1",payload:{status:"OBSERVED",recorded_at:new Date().toISOString()}});void trackPhase10ProductEvent("phase10.fundamental_observation","fundamental_intelligence",{symbol});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to record fundamental observation.");}finally{setBusy(false);}};
 const createModel=async()=>{try{setBusy(true);await createPhase10Model({name:`Quality model ${models.length+1}`,model_type:"QUALITY_SCORING",description:"Governed candidate; no automatic promotion."});void trackPhase10ProductEvent("phase10.model_candidate_created","model_governance",{});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to register model.");}finally{setBusy(false);}};
 const addVersion=async(model:ResearchModel)=>{try{setBusy(true);await createPhase10ModelVersion(model.id,{version:`0.1.${model.versions.length+1}`,dataset_version:"dataset-pending",feature_version:"features-pending",training_period_start:"2025-01-01",training_period_end:"2025-12-31",validation_period_start:"2026-01-01",validation_period_end:"2026-03-31",test_period_start:"2026-04-01",test_period_end:"2026-06-30",calibration:{error:1},test_results:{sample_size:0},performance_by_regime:{},degradation_monitoring:{status:"UNKNOWN"}});void trackPhase10ProductEvent("phase10.model_version_created","model_governance",{model_id:model.id});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create model version.");}finally{setBusy(false);}};
 const evaluate=async(id:string)=>{try{setBusy(true);await evaluatePhase10Model(id,{test_results:{sample_size:100},calibration:{error:0.2},performance_by_regime:{UNKNOWN:{sample_size:100}},degradation_monitoring:{status:"STABLE"}});void trackPhase10ProductEvent("phase10.model_evaluated","model_governance",{version_id:id});await load();}catch(e){setError(e instanceof Error?e.message:"Evaluation failed.");}finally{setBusy(false);}};
 const promote=async(id:string)=>{try{setBusy(true);await promotePhase10Model(id);void trackPhase10ProductEvent("phase10.model_promoted","model_governance",{version_id:id,manual:true});await load();}catch(e){setError(e instanceof Error?e.message:"Promotion blocked by governance checks.");}finally{setBusy(false);}};
 const rollback=async(id:string)=>{try{setBusy(true);await rollbackPhase10Model(id,"Manual rollback from Phase 10 governance workspace.");void trackPhase10ProductEvent("phase10.model_rollback","model_governance",{version_id:id});await load();}catch(e){setError(e instanceof Error?e.message:"Rollback failed.");}finally{setBusy(false);}};
 return <div className="app"><main><section className="hero dashboard-hero"><div><div className="eyebrow">Phase 10 · Mature platform layer</div><h2>Optimization, advanced intelligence and controlled expansion.</h2><p>One workspace connects market structure, research events, fundamentals, governed models and product telemetry without allowing unvalidated models to become active.</p></div><div className="hero-stat"><ShieldCheck size={20}/><strong>{overview?.model_governance.models??0}</strong><span>governed models</span></div></section>
 {error&&<div className="error"><Activity size={17}/>{error}</div>}
 <section className="panel"><div className="panel-head"><div><h3>Advanced research chart</h3><span>Completed candles with Phase 6 structure/liquidity/SMC events, Phase 10 signals/research events and provider catalysts.</span></div><button className="refresh" disabled={busy} onClick={()=>void load()}><RefreshCw size={15}/>Refresh</button></div><div className="phase10-toolbar"><label>Instrument<select value={symbol} onChange={e=>setSymbol(e.target.value)} disabled={busy}>{SYMBOLS.map(s=><option key={s}>{s}</option>)}</select></label><label>Timeframe<select value={timeframe} onChange={e=>setTimeframe(e.target.value)} disabled={busy}>{TIMEFRAMES.map(s=><option key={s}>{s}</option>)}</select></label><button onClick={()=>void addResearchEvent()} disabled={busy}>Add research annotation</button></div>{analysis?<AdvancedResearchChart analysis={analysis} events={chartEvents}/>:<div className="phase10-chart-empty">Loading validated completed candles…</div>}<div className="phase10-chart-contract"><ShieldCheck size={15}/><span>{eventCount} research, structure and catalyst events · chart uses completed-candle API data and never invents future bars.</span></div></section>
 <section className="workspace-grid"><section className="panel"><div className="panel-head"><div><h3><Database size={17}/> Fundamental intelligence</h3><span>Financial statements, earnings, valuation, analyst revisions, corporate actions and fundamental trends.</span></div><button onClick={()=>void recordFundamental()} disabled={busy}>Record observation</button></div>{providerFundamentals.length?providerFundamentals.slice(0,12).map(item=><article className="phase10-fundamental" key={item.id}><div><strong>{item.title}</strong><span>{item.event_type} · {item.provider} · {fmtTime(item.event_timestamp)}</span></div><div className="phase10-fundamental-values"><span>Actual {item.actual??"—"}</span><span>Estimate {item.estimate??"—"}</span><span>Surprise {item.surprise??"—"}</span></div></article>):fundamentals.length?fundamentals.map(item=><article className="phase10-fundamental" key={item.id}><div><strong>{item.observation_type}</strong><span>{item.symbol} · {item.source??"manual"} · {fmtTime(item.observed_at)}</span></div></article>):<div className="settings-health-empty">No fundamental observations for {symbol}.</div>}</section>
 <section className="panel"><h3><Activity size={17}/> Product & platform telemetry</h3><div className="phase10-metrics"><div><strong>{overview?.product_intelligence.tracked_events??0}</strong><span>tracked product events</span></div><div><strong>{overview?.advanced_charting.events??0}</strong><span>chart events</span></div><div><strong>{overview?.fundamental_intelligence.observations??0}</strong><span>fundamental observations</span></div></div><p className="muted">Structured events now record Phase 10 feature usage, providing the foundation for adoption, research frequency, signal-analysis usage, AI usage and infrastructure-cost cohorts.</p></section></section>
 <section className="panel"><div className="panel-head"><div><h3><BrainCircuit size={17}/> Strict model governance</h3><span>Every version records dataset, feature, train/validation/test periods, calibration, regime performance and degradation state.</span></div><button onClick={()=>void createModel()} disabled={busy}><Sparkles size={15}/>Register model candidate</button></div><div className="phase10-governance-note"><ShieldCheck size={16}/> Automatic promotion: <strong>disabled</strong>. Evaluation is required before manual promotion; rollback remains explicit and audited.</div>{models.length?models.map(model=><article className="phase10-model" key={model.id}><div className="phase10-model-head"><div><strong>{model.name}</strong><span>{model.model_type} · {model.active_version_id?"active version set":"no active version"}</span></div><button onClick={()=>void addVersion(model)} disabled={busy}>New version</button></div>{model.versions.map(v=><div className="phase10-version" key={v.id}><div><strong>{v.version}</strong><span>{v.status} · dataset {v.dataset_version} · features {v.feature_version} · test {v.test_passed?"passed":"pending"}</span></div><div className="phase10-actions">{v.status!=="APPROVED"&&<button onClick={()=>void evaluate(v.id)} disabled={busy}>Evaluate</button>}{v.test_passed&&v.status!=="APPROVED"&&<button onClick={()=>void promote(v.id)} disabled={busy}>Manual promote</button>}{v.status==="APPROVED"&&<button onClick={()=>void rollback(v.id)} disabled={busy}>Rollback</button>}</div></div>)}</article>):<div className="settings-health-empty">No model candidates registered.</div>}</section>
 <section className="workspace-grid"><section className="panel"><h3><Activity size={17}/> Optimization controls</h3><ul className="phase10-checks"><li>Provider-independent cache and last-known-good recovery remain authoritative.</li><li>Scheduled maintenance expires Phase 10 cache entries.</li><li>Background research, webhook, export and maintenance jobs run through the existing scheduler.</li><li>Model degradation is observable without automatic rollback or promotion.</li><li>Product telemetry is stored as structured events for later cohort analysis.</li></ul></section><section className="panel"><h3><ShieldCheck size={17}/> Expansion gates</h3><ul className="phase10-checks"><li>Statistical calibration requires recorded outcomes.</li><li>ML-assisted scoring requires versioned datasets and feature definitions.</li><li>Similarity and regime-conditioned models require explicit evaluation evidence.</li><li>Predictive models require separate train, validation and test periods.</li><li>No automatic model promotion.</li></ul></section></section>
 <footer>Research and decision support only. No autonomous trading or automatic model promotion.</footer></main></div>;
}
