const BASE=((import.meta.env.VITE_API_BASE_URL as string|undefined)?.trim()||"https://research-76vr.onrender.com").replace(/\/$/,"");
async function request<T>(path:string,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);if(init.body&&!headers.has("Content-Type"))headers.set("Content-Type","application/json");if(init.method&&init.method!=="GET"){let csrf: string|null=null;try{csrf=sessionStorage.getItem("mr_csrf_token")}catch{};if(!csrf){const r=await fetch(`${BASE}/api/auth/csrf`,{credentials:"include"});csrf=r.headers.get("X-CSRF-Token");try{if(csrf)sessionStorage.setItem("mr_csrf_token",csrf)}catch{}}if(csrf)headers.set("X-CSRF-Token",csrf)}const r=await fetch(`${BASE}${path}`,{...init,headers,credentials:"include"});if(!r.ok){let d="Request failed";try{const j=await r.json();d=typeof j.detail==="string"?j.detail:d}catch{};throw new Error(d)}return r.status===204?undefined as T:await r.json() as T;}
export type Phase10Overview={model_governance:{models:number;versions_by_status:Record<string,number>;automatic_promotion:boolean};advanced_charting:{events:number;event_types:string[]};fundamental_intelligence:{observations:number;types:string[]};product_intelligence:{tracked_events:number};optimization:{cache_namespace:string;maintenance:string}};
export type ChartEvent={id:string;symbol:string;timeframe:string;event_type:string;occurred_at:string;price:number|null;payload:Record<string,unknown>;source:string|null;engine_version:string|null};
export type FundamentalObservation={id:string;symbol:string;observation_type:string;period_start:string|null;period_end:string|null;observed_at:string;source:string|null;source_version:string|null;payload:Record<string,unknown>};
export type ModelVersion={id:string;model_id:string;version:string;status:string;dataset_version:string;feature_version:string;training_period_start:string;training_period_end:string;validation_period_start:string;validation_period_end:string;test_period_start:string;test_period_end:string;calibration:Record<string,unknown>;test_results:Record<string,unknown>;performance_by_regime:Record<string,unknown>;degradation_monitoring:Record<string,unknown>;test_passed:boolean;promotion_actor_user_id:string|null;promoted_at:string|null;rollback_reason:string|null};
export type ResearchModel={id:string;name:string;model_type:string;description:string|null;active_version_id:string|null;versions:ModelVersion[]};
export const getPhase10Overview=()=>request<Phase10Overview>("/api/phase10/overview");
export const getChartEvents=(symbol:string,timeframe:string)=>request<{items:ChartEvent[]}>(`/api/phase10/chart-events?symbol=${encodeURIComponent(symbol)}&timeframe=${encodeURIComponent(timeframe)}`);
export const createChartEvent=(payload:Record<string,unknown>)=>request<{item:ChartEvent}>("/api/phase10/chart-events",{method:"POST",body:JSON.stringify(payload)});
export const getFundamentals=(symbol:string)=>request<{items:FundamentalObservation[]}>(`/api/phase10/fundamentals?symbol=${encodeURIComponent(symbol)}`);
export const createFundamental=(payload:Record<string,unknown>)=>request<{item:FundamentalObservation}>("/api/phase10/fundamentals",{method:"POST",body:JSON.stringify(payload)});
export const getPhase10Models=()=>request<{items:ResearchModel[]}>("/api/phase10/models");
export const createPhase10Model=(payload:Record<string,unknown>)=>request<{item:ResearchModel}>("/api/phase10/models",{method:"POST",body:JSON.stringify(payload)});
export const createPhase10ModelVersion=(modelId:string,payload:Record<string,unknown>)=>request<{item:ModelVersion}>(`/api/phase10/models/${encodeURIComponent(modelId)}/versions`,{method:"POST",body:JSON.stringify(payload)});
export const evaluatePhase10Model=(versionId:string,payload:Record<string,unknown>)=>request<{item:ModelVersion}>(`/api/phase10/model-versions/${encodeURIComponent(versionId)}/evaluate`,{method:"POST",body:JSON.stringify(payload)});
export const promotePhase10Model=(versionId:string)=>request<{item:ModelVersion}>(`/api/phase10/model-versions/${encodeURIComponent(versionId)}/promote`,{method:"POST"});
export const rollbackPhase10Model=(versionId:string,reason:string)=>request<{item:ModelVersion}>(`/api/phase10/model-versions/${encodeURIComponent(versionId)}/rollback`,{method:"POST",body:JSON.stringify({reason})});
