import { useCallback,useEffect,useState } from "react";
import { Activity, BrainCircuit, Database, LineChart, RefreshCw, ShieldCheck, Sparkles } from "lucide-react";
import { ApiError, getCurrentUser, User } from "./api";
import { getPhase10Overview, getPhase10Models, getChartEvents, getFundamentals, createChartEvent, createFundamental, createPhase10Model, createPhase10ModelVersion, evaluatePhase10Model, promotePhase10Model, rollbackPhase10Model, Phase10Overview, ResearchModel, ChartEvent, FundamentalObservation } from "./phase10Api";

export default function Phase10Page({user,onLogout}:{user:User;onLogout:()=>void}){
 const [overview,setOverview]=useState<Phase10Overview|null>(null); const [models,setModels]=useState<ResearchModel[]>([]); const [events,setEvents]=useState<ChartEvent[]>([]); const [fundamentals,setFundamentals]=useState<FundamentalObservation[]>([]); const [symbol,setSymbol]=useState("BTC/USD"); const [timeframe,setTimeframe]=useState("H1"); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{try{setError(null);const [o,m,e,f]=await Promise.all([getPhase10Overview(),getPhase10Models(),getChartEvents(symbol,timeframe),getFundamentals(symbol)]);setOverview(o);setModels(m);setEvents(e.items);setFundamentals(f.items);}catch(e){if(e instanceof ApiError&&e.status===401)onLogout();else setError(e instanceof Error?e.message:"Unable to load Phase 10 intelligence.");}},[onLogout,symbol,timeframe]);
 useEffect(()=>{void load();},[load]);
 const addDemoEvent=async()=>{try{setBusy(true);await createChartEvent({symbol,timeframe,event_type:"RESEARCH",payload:{note:"Research event layer ready for provider/engine ingestion."}});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create chart event.");}finally{setBusy(false);}};
 const addFundamental=async()=>{try{setBusy(true);await createFundamental({symbol,observation_type:"FUNDAMENTAL_TREND",payload:{status:"PENDING_SOURCE_INGESTION",note:"Schema is ready; connect validated fundamental provider data."}});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create fundamental observation.");}finally{setBusy(false);}};
 const createModel=async()=>{try{setBusy(true);await createPhase10Model({name:`Research quality model ${models.length+1}`,model_type:"QUALITY_SCORING",description:"Governed model candidate; no automatic promotion."});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create model.");}finally{setBusy(false);}};
 const addVersion=async(model:ResearchModel)=>{try{setBusy(true);await createPhase10ModelVersion(model.id,{version:`0.1.${model.versions.length+1}`,dataset_version:"dataset-pending",feature_version:"features-pending",training_period_start:"2025-01-01",training_period_end:"2025-12-31",validation_period_start:"2026-01-01",validation_period_end:"2026-03-31",test_period_start:"2026-04-01",test_period_end:"2026-06-30",calibration:{error:1},test_results:{sample_size:0},performance_by_regime:{},degradation_monitoring:{status:"UNKNOWN"}});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create model version.");}finally{setBusy(false);}};
 const evaluate=async(id:string)=>{try{setBusy(true);await evaluatePhase10Model(id,{test_results:{sample_size:100},calibration:{error:0.2},performance_by_regime:{UNKNOWN:{sample_size:100}},degradation_monitoring:{status:"STABLE"}});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to evaluate model.");}finally{setBusy(false);}};
 const promote=async(id:string)=>{try{setBusy(true);await promotePhase10Model(id);await load();}catch(e){setError(e instanceof Error?e.message:"Promotion blocked by governance checks.");}finally{setBusy(false);}};
 const rollback=async(id:string)=>{try{setBusy(true);await rollbackPhase10Model(id,"Manual rollback from Phase 10 governance workspace.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to roll back model.");}finally{setBusy(false);}};
 return <div className="app"><header className="topbar"><div className="product-brand"><img src="/profitforge-logo.svg" alt="ProfitForge"/><div><div className="eyebrow">ProfitForge Intelligence</div><h1>Optimization & Advanced Intelligence</h1></div></div><div className="topbar-actions"><span className="user-email">{user.email}</span></div></header><main>
 <section className="hero dashboard-hero"><div><div className="eyebrow">Phase 10 · Mature platform layer</div><h2>Optimization, intelligence and controlled expansion.</h2><p>Advanced capabilities are versioned, observable and governed. Models never promote themselves.</p></div><div className="hero-stat"><ShieldCheck size={20}/><strong>{overview?.model_governance.models??0}</strong><span>governed models</span></div></section>
 {error&&<div className="error"><Activity size={17}/>{error}</div>}
 <section className="workspace-grid">
  <section className="panel"><div className="panel-head"><div><h3><LineChart size={17}/> Advanced chart event layer</h3><span>Regime, SMC, BOS/CHOCH, liquidity, signals, entries, exits, SL/TP, outcomes, research events and catalysts.</span></div><button className="refresh" disabled={busy} onClick={()=>void load()}><RefreshCw size={15}/>Refresh</button></div><div className="phase10-toolbar"><label>Symbol<input value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())}/></label><label>Timeframe<select value={timeframe} onChange={e=>setTimeframe(e.target.value)}><option>H1</option><option>H4</option><option>D1</option><option>M15</option></select></label><button onClick={()=>void addDemoEvent()} disabled={busy}>Add research event</button></div><div className="phase10-events">{events.length?events.map(e=><div key={e.id}><strong>{e.event_type}</strong><span>{new Date(e.occurred_at).toLocaleString()} · {e.price??"—"}</span></div>):<div className="settings-health-empty">No chart events yet. Provider/engine ingestion can populate this layer without changing the chart contract.</div>}</div></section>
  <section className="panel"><div className="panel-head"><div><h3><Database size={17}/> Fundamental intelligence</h3><span>Statements, earnings, valuation, analyst revisions, corporate actions and fundamental trends.</span></div><button onClick={()=>void addFundamental()} disabled={busy}>Record observation</button></div>{fundamentals.length?fundamentals.map(f=><div className="phase10-row" key={f.id}><strong>{f.observation_type}</strong><span>{f.symbol} · {new Date(f.observed_at).toLocaleString()}</span></div>):<div className="settings-health-empty">No validated fundamental observations for {symbol}.</div>}</section>
 </section>
 <section className="panel"><div className="panel-head"><div><h3><BrainCircuit size={17}/> Model governance</h3><span>Dataset + feature versions, train/validation/test periods, calibration, regime performance, degradation monitoring and manual rollback.</span></div><button onClick={()=>void createModel()} disabled={busy}><Sparkles size={15}/>Register model candidate</button></div><div className="phase10-governance-note"><ShieldCheck size={16}/> Automatic promotion: <strong>disabled</strong>. A version must be explicitly evaluated and manually promoted; rollback remains available.</div>{models.length?models.map(model=><article className="phase10-model" key={model.id}><div className="phase10-model-head"><div><strong>{model.name}</strong><span>{model.model_type} · {model.active_version_id?"active version set":"no active version"}</span></div><button onClick={()=>void addVersion(model)} disabled={busy}>New version</button></div>{model.versions.map(v=><div className="phase10-version" key={v.id}><div><strong>{v.version}</strong><span>{v.status} · dataset {v.dataset_version} · features {v.feature_version}</span></div><div className="phase10-actions">{v.status!=="APPROVED"&&<button onClick={()=>void evaluate(v.id)} disabled={busy}>Evaluate</button>}{v.test_passed&&v.status!=="APPROVED"&&<button onClick={()=>void promote(v.id)} disabled={busy}>Manual promote</button>}{v.status==="APPROVED"&&<button onClick={()=>void rollback(v.id)} disabled={busy}>Rollback</button>}</div></div>)}</article>):<div className="settings-health-empty">No model candidates registered. The governance contract is ready before any ML promotion.</div>}</section>
 <section className="workspace-grid"><section className="panel"><h3><Activity size={17}/> Platform optimization</h3><div className="phase10-metrics"><div><strong>{overview?.optimization.cache_namespace??"phase10"}</strong><span>cache namespace</span></div><div><strong>{overview?.advanced_charting.events??0}</strong><span>chart events</span></div><div><strong>{overview?.product_intelligence.tracked_events??0}</strong><span>product events</span></div></div><p className="muted">Cache expiry is scheduler-maintained. API responses retain provenance and security headers, while product telemetry provides the foundation for adoption, retention, AI-usage and infrastructure-cost measurement.</p></section><section className="panel"><h3><ShieldCheck size={17}/> Expansion gates</h3><ul className="phase10-checks"><li>Statistical calibration requires recorded outcomes.</li><li>ML-assisted scoring requires versioned datasets and feature definitions.</li><li>Predictive models require separate train, validation and test periods.</li><li>Performance is tracked by regime and degradation status.</li><li>No automatic model promotion.</li></ul></section></section>
 </main></div>;
}
