import { useEffect, useState } from "react";
import { AlertTriangle, FlaskConical, Save, ShieldCheck } from "lucide-react";
import { ApiError, User } from "./api";

type Props={user:User;onLogout:()=>void;setPage:(p:any)=>void};
const csrf=()=>document.cookie.match(/(?:^|; )mr_csrf_token=([^;]+)/)?.[1]??"";
const post=async(path:string,body:any)=>{const r=await fetch(path,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(body)});if(!r.ok)throw new ApiError((await r.json()).detail??"Request failed.",r.status);return r.json();};

export default function QuantLabPage({user,onLogout}:Props){
 const [symbol,setSymbol]=useState("BTC/USD"),[field,setField]=useState("close"),[operator,setOperator]=useState("gt"),[value,setValue]=useState("100"),[exitValue,setExitValue]=useState("102");
 const [result,setResult]=useState<any>(null),[robust,setRobust]=useState<any>(null),[strategies,setStrategies]=useState<any[]>([]),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);
 const loadStrategies=async()=>{const r=await fetch("/api/quant-lab/strategies",{credentials:"include"});if(r.ok)setStrategies((await r.json()).items??[]);};
 useEffect(()=>{void loadStrategies();},[]);
 const makeBody=()=>{
  const now=Date.now(),day=86400000;
  const candles=Array.from({length:30},(_,i)=>{const p=100+i*.5;return {timestamp:new Date(now-(30-i)*day).toISOString(),open:p,high:p+2,low:p-2,close:p+1,volume:1000,symbol,timeframe:"1d",source:"research-ui",is_complete:true,features:{regime:i%2?"STRONG_TREND_UP":"RANGE",trend_aligned:i%3!==0,liquidity_sweep:i%5===0,rr:2}};});
  return {strategy:{name:"Quant Lab Builder",version:"1",direction:"LONG",timeframe:"1d",entry_rules:[{field,operator,value:field==="close"?Number(value):value}],exit_rules:[{field:"close",operator:"lt",value:Number(exitValue)}]},dataset:{symbol,timeframe:"1d",source:"research-ui",requested_at:new Date().toISOString(),candles},experiment:{dataset_version:"ui-v2-completed",strategy_version:"builder-v1",feature_version:"feature-context-v1",parameters:{field,value},costs:{},execution:{commission_bps:5,slippage_bps:2,spread_bps:2,position_size:1},train_start:new Date(now-29*day).toISOString(),train_end:new Date(now-20*day).toISOString(),validation_start:new Date(now-20*day).toISOString(),validation_end:new Date(now-10*day).toISOString(),test_start:new Date(now-10*day).toISOString(),test_end:new Date(now).toISOString()}};
 };
 const run=async()=>{setBusy(true);setError(null);try{const data=await post("/api/quant-lab/backtests",makeBody());setResult(data);setRobust(null);}catch(e){if(e instanceof ApiError&&e.status===401){onLogout();return;}setError(e instanceof Error?e.message:"Unable to run backtest.");}finally{setBusy(false);}};
 const save=async()=>{try{await post("/api/quant-lab/strategies",{name:"Quant Lab Builder",version:"1",direction:"LONG",timeframe:"1d",entry_rules:[{field,operator,value:field==="close"?Number(value):value}],exit_rules:[{field:"close",operator:"lt",value:Number(exitValue)}]});await loadStrategies();}catch(e){setError(e instanceof Error?e.message:"Unable to save strategy.");}};
 const validate=async()=>{if(!result)return;try{setRobust(await post("/api/quant-lab/robustness",{experiment:makeBody().experiment,result,sensitivity_values:{slippage_bps:[0,2,5,10],commission_bps:[0,5,10]}}));}catch(e){setError(e instanceof Error?e.message:"Unable to validate robustness.");}};
 return <div className="app"><header className="topbar"><div className="product-brand"><div><div className="eyebrow">Phase 6 · Quant Lab</div><h1>Quant Lab</h1></div></div><div className="topbar-actions"><span className="user-email">{user.email}</span><button className="logout" onClick={onLogout}>Sign out</button></div></header><main>
 <section className="hero"><div><div className="eyebrow">Observation → Hypothesis → Test → Validation → Paper Trading</div><h2>Systematic strategy research.</h2><p>Every experiment records its data, strategy, feature, parameters, costs, execution assumptions and immutable specification hash.</p></div><FlaskConical size={32}/></section>
 {error&&<div className="error"><AlertTriangle size={17}/>{error}</div>}
 <section className="panel"><div className="panel-head"><div><h3>Strategy Builder</h3><span>IF all entry rules match AND all exit rules match. Derived feature context is recorded with each completed candle.</span></div></div><div className="inline-form"><label>Asset<input value={symbol} onChange={e=>setSymbol(e.target.value)}/></label><label>Entry field<select value={field} onChange={e=>setField(e.target.value)}><option value="close">close</option><option value="regime">regime</option><option value="trend_aligned">trend_aligned</option><option value="liquidity_sweep">liquidity_sweep</option><option value="rr">rr</option></select></label><label>Operator<select value={operator} onChange={e=>setOperator(e.target.value)}><option value="gt">gt</option><option value="gte">gte</option><option value="eq">eq</option><option value="lt">lt</option><option value="lte">lte</option></select></label><label>Entry value<input value={value} onChange={e=>setValue(e.target.value)}/></label><label>Exit close &lt;<input type="number" value={exitValue} onChange={e=>setExitValue(e.target.value)}/></label><button onClick={()=>void save()}><Save size={15}/>Save version</button><button onClick={()=>void run()} disabled={busy}>{busy?"Running…":"Run backtest"}</button></div></section>
 <section className="workspace-grid"><div className="panel"><h3>Saved strategy versions</h3>{strategies.length?<div className="quotes">{strategies.slice(0,6).map(s=><div className="quote-row" key={s.id}><span>{s.name}</span><strong>v{s.version}</strong></div>)}</div>:<div className="empty">No saved versions yet.</div>}</div><div className="panel"><h3>Validation gate</h3><p className="muted">Walk-forward windows, bootstrap Monte Carlo, parameter sensitivity and explicit robustness scorecards are available after a backtest.</p><button onClick={()=>void validate()} disabled={!result}><ShieldCheck size={15}/>Run robustness validation</button></div></section>
 {result&&<section className="workspace-grid"><div className="panel"><h3>Backtest metrics</h3><div className="quotes">{Object.entries(result.metrics).filter(([k])=>!["regime_breakdown","timeframe_breakdown","r_distribution"].includes(k)).map(([k,v])=><div className="quote-row" key={k}><span>{k.replaceAll("_"," ")}</span><strong>{typeof v==="number"?Number(v).toFixed(4):String(v??"—")}</strong></div>)}</div></div><div className="panel"><h3>Anti-overfit controls</h3>{Object.entries(result.anti_overfit_checks).map(([k,v])=><div className="quote-row" key={k}><span>{k.replaceAll("_"," ")}</span><strong>{v?"PASS":"FAIL"}</strong></div>)}<div className="muted">Spec hash: {result.spec_hash}</div></div></section>}
 {robust&&<section className="panel"><h3>Robustness analysis</h3><div className="workspace-grid"><div><div className="quote-row"><span>Monte Carlo median P&amp;L</span><strong>{robust.monte_carlo.median_pnl.toFixed(4)}</strong></div><div className="quote-row"><span>5th percentile P&amp;L</span><strong>{robust.monte_carlo.p05_pnl.toFixed(4)}</strong></div><div className="quote-row"><span>Loss probability</span><strong>{(robust.monte_carlo.probability_of_loss*100).toFixed(1)}%</strong></div></div><div>{Object.entries(robust.scorecard).map(([k,v])=><div className="quote-row" key={k}><span>{k.replaceAll("_"," ")}</span><strong>{v?"PASS":"WARN"}</strong></div>)}</div></div>{robust.warnings.map((w:string)=><div className="muted" key={w}>{w}</div>)}</section>}
 <footer>Research and decision support only. Backtest and validation results do not establish future performance or certainty.</footer></main></div>;
}
