import { useEffect, useMemo, useState } from "react";
import { addResearchNote, deleteResearchHistory, getResearchHistory, getResearchHistoryDetail, HistoryItem, saveResearchHistory, unsaveResearchHistory } from "./researchHistoryApi";
import "./research-history.css";

type ReportPayload = { symbol?: string; generated_at?: string; market_status?: { current_price?: number; change_24h_percent?: number | null; market_regime?: string; trend?: string; momentum?: string }; overall_research_score?: number; bull_case?: string[]; bear_case?: string[]; key_risks?: string[] };
const dateLabel = (value: string) => new Date(value).toLocaleDateString([], { month: "short", day: "numeric", year: "numeric" });
const money = (value: unknown) => typeof value === "number" ? value.toLocaleString(undefined, { maximumFractionDigits: value >= 100 ? 2 : 6 }) : "Unavailable";
const pct = (value: unknown) => typeof value === "number" ? `${value >= 0 ? "+" : ""}${value.toFixed(2)}%` : "Unavailable";

export default function ResearchHistoryPage() {
  const [items, setItems] = useState<HistoryItem[]>([]); const [selected, setSelected] = useState<HistoryItem | null>(null); const [notes, setNotes] = useState<{ id: string; note: string; created_at: string }[]>([]); const [note, setNote] = useState(""); const [filter, setFilter] = useState<"ALL" | "REPORT" | "AI_ANALYSIS" | "SEARCH">("ALL"); const [savedOnly, setSavedOnly] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = async () => { setLoading(true); setError(null); try { const next = await getResearchHistory({ type: filter === "ALL" ? undefined : filter, saved: savedOnly ? true : undefined }); setItems(next); if (selected) { const detail = await getResearchHistoryDetail(selected.id); setSelected(detail.item); setNotes(detail.notes); } } catch (err) { setError(err instanceof Error ? err.message : "Unable to load research history."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [filter, savedOnly]);
  const report = useMemo<ReportPayload | null>(() => selected?.record_type === "REPORT" ? selected.payload as ReportPayload : null, [selected]);
  const select = async (item: HistoryItem) => { setSelected(item); try { const detail = await getResearchHistoryDetail(item.id); setSelected(detail.item); setNotes(detail.notes); } catch (err) { setError(err instanceof Error ? err.message : "Unable to open history record."); } };
  const toggleSaved = async () => { if (!selected) return; try { const next = selected.saved ? (await unsaveResearchHistory(selected.id), { ...selected, saved: false }) : await saveResearchHistory(selected.id); setSelected(next); setItems(current => current.map(item => item.id === next.id ? next : item)); } catch (err) { setError(err instanceof Error ? err.message : "Unable to update saved state."); } };
  const addNote = async () => { if (!selected || !note.trim()) return; try { const created = await addResearchNote(selected.id, note.trim()); setNotes(current => [created, ...current]); setNote(""); } catch (err) { setError(err instanceof Error ? err.message : "Unable to save note."); } };
  const remove = async () => { if (!selected || !window.confirm("Delete this history record?")) return; try { await deleteResearchHistory(selected.id); setItems(current => current.filter(item => item.id !== selected.id)); setSelected(null); setNotes([]); } catch (err) { setError(err instanceof Error ? err.message : "Unable to delete history record."); } };

  return <section className="research-history-page"><div className="history-hero"><div><div className="eyebrow">Phase 11 · Research History</div><h1>Research History</h1><p>Return to prior reports, searches, symbols, deterministic indicators/regimes, AI analyses and personal research notes.</p></div><div className="history-filters"><label>Type<select value={filter} onChange={e => setFilter(e.target.value as typeof filter)}><option value="ALL">All activity</option><option value="REPORT">Reports</option><option value="SEARCH">Searches</option><option value="AI_ANALYSIS">AI analyses</option></select></label><label className="history-check"><input type="checkbox" checked={savedOnly} onChange={e => setSavedOnly(e.target.checked)} /> Saved only</label></div></div>
    {error && <div className="history-error">{error}</div>}
    <div className="history-layout"><div className="history-list"><div className="history-list-header"><strong>{loading ? "Loading…" : `${items.length} records`}</strong></div>{!loading && !items.length && <div className="history-empty">No research history yet. Generate a report or AI analysis to start building your research timeline.</div>}{items.map(item => <button type="button" className={`history-row ${selected?.id === item.id ? "selected" : ""}`} key={item.id} onClick={() => void select(item)}><span className="history-date">{dateLabel(item.created_at)}</span><strong>{item.symbol ?? "Research"}</strong><span>{item.title ?? item.record_type}</span><span className="history-type">{item.record_type}{item.saved ? " · SAVED" : ""}</span></button>)}</div>
      <div className="history-detail">{!selected && <div className="history-placeholder"><h2>Select a research record</h2><p>Your saved timeline stays associated with your account and can be reopened later.</p></div>}{selected && <><div className="detail-head"><div><div className="eyebrow">{selected.record_type}</div><h2>{selected.title ?? selected.symbol ?? "Research record"}</h2><p>{dateLabel(selected.created_at)}{selected.query ? ` · ${selected.query}` : ""}</p></div><div className="detail-actions"><button type="button" onClick={() => void toggleSaved()}>{selected.saved ? "Unsave" : "Save report"}</button><button type="button" className="danger" onClick={() => void remove()}>Delete</button></div></div>
        {report && <div className="history-report-summary"><div><span>Current Price</span><strong>{money(report.market_status?.current_price)}</strong></div><div><span>24H Change</span><strong>{pct(report.market_status?.change_24h_percent)}</strong></div><div><span>Regime</span><strong>{report.market_status?.market_regime ?? "Unavailable"}</strong></div><div><span>Score</span><strong>{report.overall_research_score ?? "—"} / 100</strong></div><div><span>Trend</span><strong>{report.market_status?.trend ?? "Unavailable"}</strong></div><div><span>Momentum</span><strong>{report.market_status?.momentum ?? "Unavailable"}</strong></div></div>}
        {selected.record_type !== "REPORT" && <div className="history-payload"><h3>{selected.record_type === "AI_ANALYSIS" ? "AI analysis" : "Search"}</h3><pre>{selected.payload?.report ? String(selected.payload.report) : JSON.stringify(selected.payload, null, 2)}</pre></div>}
        <div className="history-notes"><h3>My notes</h3><div className="note-entry"><textarea value={note} onChange={e => setNote(e.target.value)} maxLength={5000} placeholder="Add a note about this research…" /><button type="button" onClick={() => void addNote()} disabled={!note.trim()}>Add note</button></div>{notes.map(item => <article key={item.id}><p>{item.note}</p><time>{dateLabel(item.created_at)}</time></article>)}</div></>}
      </div></div></section>;
}
