import { useCallback, useEffect, useState } from "react";
import { RefreshCw, Trash2 } from "lucide-react";
import { createResearchWatchpoint, deleteResearchWatchpoint, getResearchCatalysts, getResearchComparison, getResearchTimeline, getResearchWatchpointEvents, getResearchWatchpoints, saveResearchSnapshot, ResearchCatalyst, ResearchComparison, ResearchSnapshot, ResearchWatchpoint, ResearchWatchpointEvent } from "./researchIntelligenceApi";
import "./research-intelligence.css";

const ASSETS = ["BTC/USD","ETH/USD","SOL/USD","EUR/USD","GBP/USD","USD/JPY","NVDA","AAPL","MSFT","SPY"];
const BASELINES = [["previous_session","Previous session"],["previous_report","Previous report"],["previous_day","Previous day"],["previous_week","Previous week"],["saved","Saved research snapshot"]] as const;
const time = (value: string) => new Date(value).toLocaleString([], { dateStyle: "medium", timeStyle: "short" });
const value = (item: unknown) => item == null ? "Unavailable" : typeof item === "object" ? JSON.stringify(item) : String(item);

export default function ResearchIntelligencePage() {
  const [symbol,setSymbol]=useState("BTC/USD"); const [baseline,setBaseline]=useState("previous_session");
  const [timeline,setTimeline]=useState<ResearchSnapshot[]>([]); const [comparison,setComparison]=useState<ResearchComparison|null>(null);
  const [watchpoints,setWatchpoints]=useState<ResearchWatchpoint[]>([]); const [events,setEvents]=useState<ResearchWatchpointEvent[]>([]); const [catalysts,setCatalysts]=useState<ResearchCatalyst[]>([]);
  const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null);
  const [watchName,setWatchName]=useState(""); const [watchField,setWatchField]=useState("market_regime"); const [watchOperator,setWatchOperator]=useState("eq"); const [watchValue,setWatchValue]=useState("STRONG_TREND_DOWN");

  const load=useCallback(async()=>{setLoading(true);setError(null);try{const [tl,cmp,wp,ev,cat]=await Promise.all([getResearchTimeline(symbol),getResearchComparison(symbol,baseline),getResearchWatchpoints(symbol),getResearchWatchpointEvents(),getResearchCatalysts(symbol)]);setTimeline(tl);setComparison(cmp);setWatchpoints(wp);setEvents(ev);setCatalysts(cat);}catch(e){setError(e instanceof Error?e.message:"Unable to load research intelligence.");}finally{setLoading(false);}},[symbol,baseline]);
  useEffect(()=>{void load();},[load]);

  const addWatchpoint=async()=>{if(!watchName.trim())return;try{await createResearchWatchpoint({symbol,name:watchName.trim(),condition_type:watchField==="support"?"SUPPORT_LOSS":watchField==="market_regime"?"FIELD_EQUALS":"FIELD_THRESHOLD",field:watchField,operator:watchOperator,value:watchField==="research_score"||watchField==="momentum"||watchField==="volatility_percent"?Number(watchValue):watchValue});setWatchName("");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create watchpoint.");}};
  const removeWatchpoint=async(id:string)=>{try{await deleteResearchWatchpoint(id);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to delete watchpoint.");}};

  return <section className="research-intelligence-page">
    <div className="ri-hero"><div><div className="eyebrow">Phase 4 · Research Intelligence</div><h1>What changed?</h1><p>Persistent market intelligence compares the current research state with earlier observed states and preserves the evidence behind important claims.</p></div>
      <div className="ri-controls"><label>Asset<select value={symbol} onChange={e=>setSymbol(e.target.value)}>{ASSETS.map(x=><option key={x}>{x}</option>)}</select></label><label>Compare against<select value={baseline} onChange={e=>setBaseline(e.target.value)}>{BASELINES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><button onClick={()=>void load()} disabled={loading}><RefreshCw size={15}/>{loading?"Refreshing…":"Refresh"}</button></div>
    </div>
    {error&&<div className="ri-error">{error}</div>}
    <div className="ri-grid">
      <section className="ri-panel ri-timeline"><div className="ri-head"><div><h2>Research timeline</h2><span>Persistent snapshots for {symbol}</span></div></div>{!timeline.length?<div className="ri-empty">Generate a research report for this asset to start the timeline.</div>:<div className="ri-timeline-list">{timeline.map((item,index)=><article key={item.id} className="ri-timeline-item"><div className="ri-dot"/><div><strong>{item.snapshot_type}</strong><time>{time(item.snapshot_at)}</time><p>Engine {item.engine_version} · {index===0?"Current state":"Historical state"}</p></div></article>)}</div>}</section>
      <section className="ri-panel"><div className="ri-head"><div><h2>What Changed?</h2><span>{comparison?.summary??"Waiting for a comparison"}</span></div>{comparison?.current&&<button className="ri-save" onClick={async()=>{try{await saveResearchSnapshot(comparison.current.id);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to save research snapshot.");}}}>Save current snapshot</button>}</div>{comparison?.baseline&&<div className="ri-baseline">Current {time(comparison.current.snapshot_at)} · baseline {time(comparison.baseline.snapshot_at)}</div>}{comparison?.changes.length?<div className="ri-changes">{comparison.changes.map((item,i)=><div className="ri-change" key={i}><div><strong>{item.category}</strong><span>{item.field}</span></div><div><code>{value(item.previous)}</code><b>→</b><code>{value(item.current)}</code></div></div>)}</div>:<div className="ri-empty">{comparison?.summary??"No comparison available."}</div>}<p className="ri-note">{comparison?.evidence_note}</p></section>
    </div>
    <div className="ri-grid">
      <section className="ri-panel"><div className="ri-head"><div><h2>Research watchpoints</h2><span>Trigger only on a transition into a watched condition.</span></div></div><div className="ri-form"><input placeholder="Watchpoint name" value={watchName} onChange={e=>setWatchName(e.target.value)}/><select value={watchField} onChange={e=>setWatchField(e.target.value)}><option value="market_regime">Market regime</option><option value="timeframes.4h.support">H4 support</option><option value="support">Support loss</option><option value="research_score">Research score</option><option value="momentum">Momentum</option><option value="volatility_percent">Volatility</option><option value="signal.confidence">Signal confidence</option></select><select value={watchOperator} onChange={e=>setWatchOperator(e.target.value)} disabled={watchField==="support"}><option value="eq">equals</option><option value="lt">below</option><option value="lte">at/below</option><option value="gt">above</option><option value="gte">at/above</option></select><input placeholder="Value" value={watchValue} onChange={e=>setWatchValue(e.target.value)}/><button onClick={()=>void addWatchpoint()}>Add</button></div>{!watchpoints.length?<div className="ri-empty">No watchpoints for this asset.</div>:watchpoints.map(w=><div className="ri-watch" key={w.id}><div><strong>{w.name}</strong><span>{w.condition_type} · {w.field} {w.operator} {value(w.value)}</span></div><button onClick={()=>void removeWatchpoint(w.id)} aria-label="Delete watchpoint"><Trash2 size={14}/></button></div>)}<div className="ri-events"><h3>Recent triggers</h3>{!events.length?<p>No watchpoint triggers yet.</p>:events.slice(0,8).map(e=><article key={e.id}><strong>{e.symbol}</strong><span>{e.message}</span><time>{time(e.triggered_at)}</time></article>)}</div></section>
      <section className="ri-panel"><div className="ri-head"><div><h2>Evidence / Provenance</h2><span>Claim → analysis → data → source → timestamp → method → engine</span></div></div>{comparison?.current.provenance.length?<div className="ri-provenance">{comparison.current.provenance.map(p=><article key={p.id}><strong>{p.claim_type}</strong><h3>{p.claim}</h3><p>{p.analysis}</p><dl><div><dt>Data</dt><dd>{value(p.data)}</dd></div><div><dt>Source</dt><dd>{p.sources.join(", ")}</dd></div><div><dt>Observed</dt><dd>{time(p.observed_at)}</dd></div><div><dt>Method</dt><dd>{p.method}</dd></div><div><dt>Engine</dt><dd>{p.engine_version}</dd><div><dt>Model</dt><dd>{p.model_version}</dd></div></div></dl></article>)}</div>:<div className="ri-empty">Select an asset with a persisted report snapshot to inspect provenance.</div>}</section>
    </div>
    <section className="ri-panel"><div className="ri-head"><div><h2>Catalyst / Event Intelligence</h2><span>Economic, earnings, corporate and market-news context from the configured research provider.</span></div></div>{!catalysts.length?<div className="ri-empty">No catalyst events were returned for this asset and period.</div>:<div className="ri-catalysts">{catalysts.map(c=><article key={c.id}><div><strong>{c.event_type}</strong><time>{time(c.event_timestamp)}</time></div><h3>{c.title}</h3><p>{c.source}{c.affected_assets.length?" · "+c.affected_assets.join(", "):""}</p>{Object.keys(c.market_reaction).length>0&&<p>Historical reaction: {value(c.market_reaction)}</p>}{c.source_url&&<a href={c.source_url} target="_blank" rel="noreferrer">Source</a>}</article>)}</div>}</section>
  </section>;
}
