import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, ArrowLeft, BarChart3, Play, Search, ShieldCheck } from "lucide-react";
import { ApiError, getSignalCalibration, getSignalIntelligence, getSignalReplay, getSignalSimilarity, logout, SignalCalibration, SignalExplorerResult, SignalReplay, User } from "./api";
import type { AppPage } from "./App";
import "./signal-intelligence.css";

export default function SignalIntelligencePage({user,onLogout,setPage}:{user:User;onLogout:()=>void;setPage:(p:AppPage)=>void}) {
  const [data,setData]=useState<SignalExplorerResult|null>(null); const [calibration,setCalibration]=useState<SignalCalibration|null>(null);
  const [replay,setReplay]=useState<SignalReplay|null>(null); const [similar,setSimilar]=useState<SignalExplorerResult|null>(null);
  const [filters,setFilters]=useState({symbol:"",timeframe:"",regime:"",min_confidence:"",max_confidence:"",min_rr:"",session:"",outcome:"",engine_version:"",structure:"",from_date:"",to_date:""});
  const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const [d,c]=await Promise.all([getSignalIntelligence(filters),getSignalCalibration()]);setData(d);setCalibration(c);}catch(e){if(e instanceof ApiError&&e.status===401){onLogout();return;}setError(e instanceof Error?e.message:"Unable to load signal intelligence.");}finally{setLoading(false);}},[filters,onLogout]);
  useEffect(()=>{void load();},[]);
  const run=()=>void load();
  const inspect=async(id:string)=>{try{setReplay(await getSignalReplay(id));setSimilar(await getSignalSimilarity(id));}catch(e){setError(e instanceof Error?e.message:"Unable to load signal replay.");}};
  const set=(key:keyof typeof filters,v:string)=>setFilters(x=>({...x,[key]:v}));
  return <div className="app"><header className="topbar"><div><div className="eyebrow">Adaptive Intelligence</div><h1>Market Research</h1></div><nav className="main-nav"><button className="nav-button" onClick={()=>setPage("signals")}><ArrowLeft size={15}/> Signals</button><button className="nav-button active">Signal Intelligence</button></nav><div className="topbar-actions"><span className="user-email">{user.email}</span><button className="logout" onClick={()=>void(async()=>{try{await logout()}finally{onLogout()}})()}>Sign out</button></div></header>
  <main><section className="hero"><div><div className="eyebrow">Pro intelligence · outcomes & calibration</div><h2>How have signals like this actually performed?</h2><p>Historical observations are separated from inference. Calibration and similarity statistics remain suppressed until their minimum sample thresholds are met.</p></div><div className="hero-stat"><ShieldCheck size={20}/><strong>{data?.total??0}</strong><span>matching observations</span></div></section>
  {error&&<div className="error"><AlertTriangle size={17}/>{error}</div>}
  <section className="panel intelligence-filters"><div className="panel-head"><div><h3>Historical Signal Explorer</h3><span>Filter the persisted signal-performance dataset.</span></div><button className="refresh" onClick={run} disabled={loading}><Search size={15}/>{loading?"Searching":"Apply filters"}</button></div><div className="filter-grid">
  {([["symbol","Asset"],["timeframe","Timeframe"],["regime","Regime"],["session","Session"],["outcome","Outcome"],["engine_version","Engine version"],["min_confidence","Min confidence"],["max_confidence","Max confidence"],["min_rr","Min RR"],["structure","Structure"],["from_date","From date"],["to_date","To date"]] as const).map(([k,l])=><label key={k}>{l}<input value={filters[k]} onChange={e=>set(k,e.target.value)} placeholder={k.includes("confidence")?"0.80":""}/></label>)}
  </div></section>
  {data&&<section className="panel"><div className="panel-head"><div><h3>Signal Performance Database</h3><span>{data.sample_size_note}</span></div></div><div className="intel-table"><div className="intel-row intel-head"><span>Signal</span><span>Confidence</span><span>RR</span><span>Regime</span><span>Outcome</span><span>Engine</span><span/></div>{data.signals.map(s=><div className="intel-row" key={s.id}><span><strong>{s.symbol}</strong><small>{s.direction} · {s.timeframe} · {s.strategy}</small></span><span>{Math.round(s.confidence*100)}%</span><span>{s.risk_reward?.toFixed(2)??"—"}</span><span>{s.regime??"—"}</span><span>{s.outcome}</span><span>{s.signal_engine_version}</span><button onClick={()=>void inspect(s.signal_id)}>Inspect</button></div>)}</div></section>}
  {calibration&&<section className="panel"><div className="panel-head"><div><h3><BarChart3 size={17}/> Confidence Calibration</h3><span>Minimum sample: {calibration.minimum_sample_size} resolved outcomes per bucket.</span></div></div><div className="calibration-grid">{calibration.buckets.map(b=><article key={b.label}><strong>{b.label}</strong><span>{b.sample_size} observations</span><b>{b.statistically_meaningful&&b.observed_outcome_rate!=null?Math.round(b.observed_outcome_rate*100)+"%":"Insufficient sample"}</b><small>{b.note}</small></article>)}</div></section>}
  {replay&&<section className="panel"><div className="panel-head"><div><h3><Play size={17}/> Signal Replay · {replay.signal.symbol}</h3><span>{replay.methodology_note}</span></div></div><div className="replay-timeline">{replay.chronological_states.map((state,i)=><div key={String(state.timestamp)}><span>{i+1}</span><strong>{new Date(String(state.timestamp)).toLocaleString()}</strong><small>Regime {String(state.regime)} · Structure {String(state.structure)} · MTF {JSON.stringify(state.mtf_evidence)}</small></div>)}</div></section>}
  {similar&&<section className="panel"><div className="panel-head"><div><h3>Historical Similarity</h3><span>{similar.sample_size_note}</span></div></div><div className="similar-grid">{similar.signals.slice(0,20).map(s=><div key={s.id}><strong>{s.symbol} · {s.timeframe}</strong><span>{s.regime} · {Math.round(s.confidence*100)}% · RR {s.risk_reward?.toFixed(2)??"—"}</span><b>{s.outcome}</b></div>)}</div></section>}
  <footer>Observed outcome rates are descriptive statistics, not guarantees. Same-candle target/stop touches remain ambiguous under OHLC data.</footer></main></div>;
}