import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, Database, Download, HardDrive, LockKeyhole, RefreshCw, Trash2 } from "lucide-react";
import type { PreferencesDraft, SystemStatus } from "../settingsApi";
import { clearServerCache, deleteResearchHistory, exportAccountData, exportReports, exportResearch, exportWatchlists, getSystemStatus } from "../settingsApi";
import { SelectField, SettingField, SettingsSection, Toggle } from "./SettingsSection";

interface Props { settings: PreferencesDraft; update: <K extends keyof PreferencesDraft>(group: K, patch: Partial<PreferencesDraft[K]>) => void; }

const retentionOptions = [
  { value: "30", label: "30 days" }, { value: "90", label: "90 days" }, { value: "365", label: "1 year" }, { value: "730", label: "2 years" }, { value: "3650", label: "10 years" }, { value: "0", label: "Forever" },
];

function statusClass(status: string): string { return status === "OPERATIONAL" || status === "CONNECTED" || status === "HEALTHY" ? "settings-status-ok" : "settings-status-warn"; }
function statusLabel(status: string): string { return status === "CONNECTED" ? "Connected" : status.charAt(0) + status.slice(1).toLowerCase(); }
function downloadBlob(blob: Blob, filename: string): void { const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; document.body.appendChild(anchor); anchor.click(); anchor.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }

export default function PrivacyDataSystemSection({ settings, update }: Props) {
  const privacy = settings.privacy_preferences;
  const [system, setSystem] = useState<SystemStatus | null>(null);
  const [loadingSystem, setLoadingSystem] = useState(true);
  const [systemError, setSystemError] = useState<string | null>(null);
  const [action, setAction] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);

  const loadSystem = useCallback(async () => { setLoadingSystem(true); setSystemError(null); try { setSystem(await getSystemStatus()); } catch (error) { setSystemError(error instanceof Error ? error.message : "Unable to load system status."); } finally { setLoadingSystem(false); } }, []);
  useEffect(() => { void loadSystem(); }, [loadSystem]);

  const runDownload = async (name: string, loader: () => Promise<Blob>, filename: string) => { setAction(name); setMessage(null); try { downloadBlob(await loader(), filename); setMessage(`${filename} generated.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Export failed."); } finally { setAction(null); } };
  const clearBrowserCache = async () => { if (!window.confirm("Clear this browser's application cache? Persistent research history, reports, watchlists and server-side data will not be deleted.")) return; setAction("browser"); setMessage(null); try { window.localStorage.clear(); if ("caches" in window) { const keys = await window.caches.keys(); await Promise.all(keys.map(key => window.caches.delete(key))); } setMessage("Browser/local application cache cleared. Persistent research data was not deleted."); } catch { setMessage("Some browser cache entries could not be cleared. Persistent research data was not modified."); } finally { setAction(null); } };
  const clearServer = async () => { if (!window.confirm("Clear the server-side market-data cache? This will not delete research history, reports, watchlists or account data.")) return; setAction("server"); setMessage(null); try { setMessage(await clearServerCache()); await loadSystem(); } catch (error) { setMessage(error instanceof Error ? error.message : "Server cache could not be cleared."); } finally { setAction(null); } };
  const clearHistory = async () => { if (!window.confirm("Delete your research history? This permanently removes report, search and AI history records. Export anything you need first.")) return; setAction("history"); setMessage(null); try { setMessage(await deleteResearchHistory()); } catch (error) { setMessage(error instanceof Error ? error.message : "Research history could not be deleted."); } finally { setAction(null); } };

  return <SettingsSection title="Privacy, Data & System" description="Control retention and persistence, export your user-owned data, and inspect real application state." icon={LockKeyhole}>
    <div className="settings-subsection">
      <h3>Privacy</h3>
      <div className="settings-control-grid"><SettingField label="Research history retention" description="Expired non-saved research history is removed when history is accessed. Saved records are preserved until explicitly deleted."><SelectField value={String(privacy.research_history_retention_days)} onChange={value => update("privacy_preferences", { research_history_retention_days: Number(value) })} options={retentionOptions} /></SettingField></div>
      <div className="settings-toggle-grid"><Toggle checked={privacy.save_generated_reports} onChange={value => update("privacy_preferences", { save_generated_reports: value })} label="Save generated reports" /><Toggle checked={privacy.save_ai_research} onChange={value => update("privacy_preferences", { save_ai_research: value })} label="Save AI research" /><Toggle checked={privacy.save_search_history} onChange={value => update("privacy_preferences", { save_search_history: value })} label="Save search history" /><Toggle checked={privacy.analytics_telemetry_enabled} onChange={value => update("privacy_preferences", { analytics_telemetry_enabled: value })} label="Analytics / telemetry preference" /></div>
      <p className="settings-section-note">Analytics / telemetry is a privacy preference. No third-party analytics collector is enabled by this setting alone.</p>
    </div>

    <div className="settings-subsection"><h3>Data management</h3><p className="settings-section-note">Exports are generated from your authenticated, user-scoped records. CSV is used for tabular research data; account data is JSON.</p><div className="settings-data-actions"><button className="settings-secondary-button" disabled={!!action} onClick={() => void runDownload("research", exportResearch, "research_export.zip")}><Download size={16} />{action === "research" ? "Preparing…" : "Export my research"}</button><button className="settings-secondary-button" disabled={!!action} onClick={() => void runDownload("reports", exportReports, "reports.csv")}><Download size={16} />{action === "reports" ? "Preparing…" : "Export reports"}</button><button className="settings-secondary-button" disabled={!!action} onClick={() => void runDownload("watchlists", exportWatchlists, "watchlists.csv")}><Download size={16} />{action === "watchlists" ? "Preparing…" : "Export watchlists"}</button><button className="settings-secondary-button" disabled={!!action} onClick={() => void runDownload("account", exportAccountData, "account_data.json")}><HardDrive size={16} />{action === "account" ? "Preparing…" : "Download account data"}</button><button className="settings-danger-button" disabled={!!action} onClick={() => void clearHistory()}><Trash2 size={16} />{action === "history" ? "Deleting…" : "Delete research history"}</button></div></div>

    <div className="settings-subsection"><div className="settings-subsection-heading"><div><h3>System</h3><p>Diagnostics are read from the application API and live market-data health service. Credentials are never displayed.</p></div><button className="settings-icon-button" type="button" onClick={() => void loadSystem()} disabled={loadingSystem} title="Refresh system status" aria-label="Refresh system status"><RefreshCw size={16} className={loadingSystem ? "settings-spin" : ""} /></button></div>{loadingSystem && !system ? <div className="settings-system-empty">Checking application services…</div> : systemError ? <div className="settings-system-error">{systemError}</div> : system ? <div className="settings-system-grid"><div><span>Application version</span><strong>{system.application_version}</strong></div><div><span>API connection</span><strong className={statusClass(system.api_connection.status)}>● {statusLabel(system.api_connection.status)}</strong></div><div><span>Authentication</span><strong className={statusClass(system.authentication.status)}>● {statusLabel(system.authentication.status)}</strong></div><div><span>Market-data service</span><strong className={statusClass(system.market_data_service.status)}>● {statusLabel(system.market_data_service.status)}</strong></div><div><span>Database</span><strong className={statusClass(system.database.status)}>● {statusLabel(system.database.status)}</strong></div><div><span>Last synchronization</span><strong>{system.last_synchronization ? new Date(system.last_synchronization).toLocaleTimeString([], { hour12: false }) + " UTC" : "Not available"}</strong></div><div><span>Cache</span><strong className={statusClass(system.cache.status)}><CheckCircle2 size={14} /> {statusLabel(system.cache.status)}</strong></div><div><span>Cache entries</span><strong>{system.cache.quote_entries} quotes · {system.cache.candle_entries} candles</strong></div></div> : null}</div>

    <div className="settings-subsection"><h3>Clear application cache</h3><p className="settings-section-note">These actions are deliberately separated. Browser/local cache affects this device only; server cache contains validated market-data snapshots. Neither action deletes persistent research history.</p><div className="settings-data-actions"><button className="settings-secondary-button" disabled={!!action} onClick={() => void clearBrowserCache()}><HardDrive size={16} />{action === "browser" ? "Clearing…" : "Clear browser / local cache"}</button><button className="settings-secondary-button" disabled={!!action} onClick={() => void clearServer()}><Database size={16} />{action === "server" ? "Clearing…" : "Clear server market-data cache"}</button></div></div>
    {message ? <div className="settings-inline-status">{message}</div> : null}
  </SettingsSection>;
}
